import { User, Event, Enrollment, Notification } from '../types';
import { format } from 'date-fns';

// Mock Users
export const mockUsers: User[] = [
  {
    id: '1',
    name: 'John Doe',
    email: 'john@example.com',
    role: 'user',
    avatar: 'https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg?auto=compress&cs=tinysrgb&w=150',
  },
  {
    id: '2',
    name: 'Jane Smith',
    email: 'jane@example.com',
    role: 'organizer',
    avatar: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=150',
  },
  {
    id: '3',
    name: 'Admin User',
    email: 'admin@example.com',
    role: 'admin',
    avatar: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=150',
  },
];

// Mock Events
export const mockEvents: Event[] = [
  {
    id: '1',
    title: 'Web Development Workshop',
    description: 'Learn the fundamentals of web development including HTML, CSS, and JavaScript. This workshop is perfect for beginners who want to start their journey in web development.',
    organizerId: '2',
    organizerName: 'Jane Smith',
    date: format(new Date(2025, 5, 15), 'yyyy-MM-dd'),
    time: '09:00 - 17:00',
    location: 'Tech Hub, San Francisco',
    category: 'Technology',
    price: 99.99,
    capacity: 50,
    enrolled: 32,
    imageUrl: 'https://images.pexels.com/photos/1181271/pexels-photo-1181271.jpeg?auto=compress&cs=tinysrgb&w=800',
    batches: [
      {
        id: '1-1',
        eventId: '1',
        name: 'Morning Session',
        startTime: '09:00',
        endTime: '12:00',
        capacity: 25,
        enrolled: 18,
      },
      {
        id: '1-2',
        eventId: '1',
        name: 'Afternoon Session',
        startTime: '13:00',
        endTime: '17:00',
        capacity: 25,
        enrolled: 14,
      },
    ],
  },
  {
    id: '2',
    title: 'Digital Marketing Conference',
    description: 'Join industry experts for a full-day conference covering the latest trends in digital marketing, SEO, and social media strategies.',
    organizerId: '2',
    organizerName: 'Jane Smith',
    date: format(new Date(2025, 6, 20), 'yyyy-MM-dd'),
    time: '10:00 - 18:00',
    location: 'Grand Conference Center, New York',
    category: 'Marketing',
    price: 149.99,
    capacity: 200,
    enrolled: 87,
    imageUrl: 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
  {
    id: '3',
    title: 'Music Festival',
    description: 'A three-day music festival featuring top artists from around the world, covering genres from rock and pop to electronic and hip-hop.',
    organizerId: '2',
    organizerName: 'Jane Smith',
    date: format(new Date(2025, 7, 5), 'yyyy-MM-dd'),
    time: '12:00 - 23:00',
    location: 'Central Park, New York',
    category: 'Entertainment',
    price: 299.99,
    capacity: 5000,
    enrolled: 3750,
    imageUrl: 'https://images.pexels.com/photos/1105666/pexels-photo-1105666.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
  {
    id: '4',
    title: 'Business Networking Mixer',
    description: 'Expand your professional network at this casual business mixer. Meet entrepreneurs, executives, and professionals from various industries.',
    organizerId: '2',
    organizerName: 'Jane Smith',
    date: format(new Date(2025, 5, 28), 'yyyy-MM-dd'),
    time: '18:00 - 21:00',
    location: 'Downtown Business Center, Chicago',
    category: 'Business',
    price: 25.00,
    capacity: 100,
    enrolled: 42,
    imageUrl: 'https://images.pexels.com/photos/3183183/pexels-photo-3183183.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
  {
    id: '5',
    title: 'Yoga Retreat',
    description: 'A weekend of rejuvenation with yoga sessions, meditation, healthy meals, and wellness workshops in a beautiful natural setting.',
    organizerId: '2',
    organizerName: 'Jane Smith',
    date: format(new Date(2025, 8, 10), 'yyyy-MM-dd'),
    time: 'All Day',
    location: 'Mountain Retreat Center, Colorado',
    category: 'Health',
    price: 399.99,
    capacity: 30,
    enrolled: 24,
    imageUrl: 'https://images.pexels.com/photos/4056535/pexels-photo-4056535.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
  {
    id: '6',
    title: 'Photography Workshop',
    description: 'Master the art of photography with hands-on training from professional photographers. Learn composition, lighting, and editing techniques.',
    organizerId: '2',
    organizerName: 'Jane Smith',
    date: format(new Date(2025, 6, 5), 'yyyy-MM-dd'),
    time: '10:00 - 16:00',
    location: 'Art Gallery, Los Angeles',
    category: 'Art',
    price: 129.99,
    capacity: 20,
    enrolled: 12,
    imageUrl: 'https://images.pexels.com/photos/1266002/pexels-photo-1266002.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
];

// Mock Enrollments
export const mockEnrollments: Enrollment[] = [
  {
    id: '1',
    userId: '1',
    eventId: '1',
    batchId: '1-1',
    status: 'confirmed',
    paymentStatus: 'completed',
    paymentId: 'pay_1234567890',
    enrollmentDate: format(new Date(2025, 4, 20), 'yyyy-MM-dd'),
  },
  {
    id: '2',
    userId: '1',
    eventId: '3',
    status: 'confirmed',
    paymentStatus: 'completed',
    paymentId: 'pay_0987654321',
    enrollmentDate: format(new Date(2025, 5, 15), 'yyyy-MM-dd'),
  },
  {
    id: '3',
    userId: '1',
    eventId: '5',
    status: 'pending',
    paymentStatus: 'pending',
    enrollmentDate: format(new Date(2025, 6, 2), 'yyyy-MM-dd'),
  },
];

// Mock Notifications
export const mockNotifications: Notification[] = [
  {
    id: '1',
    userId: '1',
    title: 'Event Reminder',
    message: 'Your Web Development Workshop starts tomorrow at 9:00 AM.',
    read: false,
    createdAt: format(new Date(2025, 5, 14), 'yyyy-MM-dd'),
    link: '/events/1',
  },
  {
    id: '2',
    userId: '1',
    title: 'Payment Confirmation',
    message: 'Your payment for the Music Festival has been confirmed.',
    read: true,
    createdAt: format(new Date(2025, 5, 15), 'yyyy-MM-dd'),
    link: '/events/3',
  },
  {
    id: '3',
    userId: '1',
    title: 'New Event Added',
    message: 'A new Photography Workshop has been added that might interest you.',
    read: false,
    createdAt: format(new Date(2025, 5, 25), 'yyyy-MM-dd'),
    link: '/events/6',
  },
];